### ISSUE TITLE
shortcode not working

### ISSUE THREAD

**Issue by tapuat** [coolvikasjain/Slider#6]
shortcode does not seem to work
see http://2c5.3db.myftpupload.com/uncategorized/test-slider/

**Comment by coolvikasjain** [comment]
DOne.
The shortcode is working now

**Comment by tapuat** [comment]
There is still an issue 
the shortcode has a slight width misalignement to the right. Each slide is not centered correctly in the slider. see page above. See red circle.
![test slider healthruwords inspirational quotes](https://cloud.githubusercontent.com/assets/812132/7869784/d8d47d82-0539-11e5-9fce-a9f61951fd3d.png)
